// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjfHfs63Qd4GlYtFsUHKE6lR35HS52kIQ',
    appId: '1:309534089444:web:5bfb9686c65ce69f5b4cf1',
    messagingSenderId: '309534089444',
    projectId: 'stylelist-15000',
    authDomain: 'stylelist-15000.firebaseapp.com',
    storageBucket: 'stylelist-15000.appspot.com',
    measurementId: 'G-LJXTZPQQSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACoIhVly5HeedQDymNHtTDPeSCs228g5w',
    appId: '1:309534089444:android:00932089e24c4a915b4cf1',
    messagingSenderId: '309534089444',
    projectId: 'stylelist-15000',
    storageBucket: 'stylelist-15000.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDovyACZP63H18ZAQFKGmjwPznUrDQzPzs',
    appId: '1:309534089444:ios:cd8271167888386d5b4cf1',
    messagingSenderId: '309534089444',
    projectId: 'stylelist-15000',
    storageBucket: 'stylelist-15000.appspot.com',
    androidClientId: '309534089444-eg8s64bqcrvpfab6gopih0fft1avrei2.apps.googleusercontent.com',
    iosClientId: '309534089444-ts2sotij871dq2hdfhrn61gjid8h9dbe.apps.googleusercontent.com',
    iosBundleId: 'com.example.stylelist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDovyACZP63H18ZAQFKGmjwPznUrDQzPzs',
    appId: '1:309534089444:ios:a3e130cf532afd255b4cf1',
    messagingSenderId: '309534089444',
    projectId: 'stylelist-15000',
    storageBucket: 'stylelist-15000.appspot.com',
    androidClientId: '309534089444-eg8s64bqcrvpfab6gopih0fft1avrei2.apps.googleusercontent.com',
    iosClientId: '309534089444-htjjql7i72au5p8sdsm2i7ja7g6kusfo.apps.googleusercontent.com',
    iosBundleId: 'com.example.stylelist.RunnerTests',
  );
}
